### ISSUE TITLE
Reg- Sharing info in Spreadsheet to be changed as Sharing info via Google Forms

### ISSUE THREAD

**Issue by rajeshkumargp** [dair-ai/d2l-study-group#3]
@omarsar , In the exercises, https://github.com/dair-ai/d2l-study-group/blob/master/exercises/section-01.md,   `Submit a link to your report using this spreadsheet.` is specified. 

1) When a person makes entries for him/her self, unknowingly they may corrupt others info.
2) Nextly, Name email ids of persons are getting shared publicly, which may get misused. 

Instead, the same functionality can be achieved using Google Forms, which will make the entries made get collected as Spreadsheet. 

Requesting you to share a link for Google Forms, instead of Spreadsheet

**Comment by omarsar** [comment]
That's absolutely right, @rajeshkumargp.

I will remove the spreadsheet link from this repo. However, as I would need to provide feedback to folks, I will have to figure out a way to do that efficiently on my end. Sending an email to each individual person will be very tedious this is the reason I used the spreadsheet initially. 

Thanks for the suggestions.

**Comment by rajeshkumargp** [comment]
> I will remove the spreadsheet link from this repo.  However, as I would need to provide feedback to folks

Suggestion :  
-  Still the form will capture information in Spreadsheet, and please have the feedback on same Spreadsheet. 
-  Hiding the email id column, while exposing the link publicly (I don't have explored this way). Aliter, another spreadsheet can be maintained for Feedback without Email id info, for exposing public link. 
- When an entry is made in form, the row number of the candidates can be mailed to refer in future - something unique to identify them.
- When sharing feedback publicly, one can learn from others feedback too. 

>  I will have to figure out a way to do that efficiently on my end. Sending an email to each individual person will be very tedious > this is the reason I used the spreadsheet initially.

Suggestion:
 A Jupyter notebook in Collab environment can be created to read info from Spreadsheet and mail candidates individually. Here, the individual can learn their feedback alone.

Reference Script:
https://codereview.stackexchange.com/questions/178144/automatically-sending-an-email-based-on-a-google-sheets-cell-value

Thanks @omarsar  for quick actions.
